apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-network
spec:
  dependsOn:
  - provider: xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2
    version: ">=v2.3.0"
  - function: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: ">=v0.6.0"